apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: three-tier-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/lovelu99/azure-devops-three-tier-gitops.git
    targetRevision: main
    path: apps/three-tier
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: three-tier

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true